services:
  csvision-frontend:
    image: nginx:latest
    ports:
      - '8080:80'
    networks:
      - CSVision_network
    volumes:
      - ../frontend:/usr/share/nginx/html
    restart: unless-stopped

  csvision-reverse-proxy:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
      - '443:443'
    networks:
      - CSVision_network
    restart: unless-stopped

  csvision-api:
    build:
      context: ./../api/
      dockerfile: ../docker/dockerfiles/Dockerfile.api
    working_dir: /app
    volumes:
      - ./../api/CSVision:/app
      - /app/bin
      - /app/obj
    ports:
      - 8001:8001 # Web port
      - 5678:5678 # Debug port
    networks:
      - CSVision_network
    restart: unless-stopped

networks:
  CSVision_network:
    driver: bridge
