services:
  csvision-web:
    image: nginx:latest
    ports:
      - '8080:80'
    networks:
      - CSVision_network
    volumes:
      - ../frontend:/usr/share/nginx/html

  csvision-reverse-proxy:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
      - '443:443'
    networks:
      - CSVision_network

  csvision-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    volumes:
      - ../api:/app
    ports:
      - '8001:8001'
    networks:
      - CSVision_network

networks:
  CSVision_network:
    driver: bridge
